# Generated by Django 3.2.8 on 2021-11-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_delete_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
