# Generated by Django 3.2.8 on 2021-11-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_airports_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
